name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.4.7
      with:
        # The Hugo version to download (if necessary) and use. Example: 0.58.2
        hugo-version: 0.68.1
        # Download (if necessary) and use Hugo extended version. Example: true
        extended: false


    - name: Build
      run: hugo --theme=book

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.4.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.tcms }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
